---
titre: Diagramme de classe
auteurice: Laurie Boucher et Jade Lirette
description: Diagramme de classe principal du système d'échecs
date-creation: 2026-02-26
date-modification: 2026-02-26
---
classDiagram

class Menu
class FormPartie {
  afficherPlateau()
}

class Echecs

class JeuEchec

class Joueur
class Partie
class Piece
class Plateau

class Pion
class Fou
class Roi
class Dame
class Tour
class Cavalier
